/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoge_org_jni_OpenSLES */

#ifndef _Included_com_xiaoge_org_jni_OpenSLES
#define _Included_com_xiaoge_org_jni_OpenSLES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoge_org_jni_OpenSLES
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoge_org_jni_OpenSLES_start
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoge_org_jni_OpenSLES
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoge_org_jni_OpenSLES_read
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoge_org_jni_OpenSLES
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoge_org_jni_OpenSLES_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoge_org_jni_OpenSLES
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoge_org_jni_OpenSLES_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
