/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_bus_JNI_Bus */

#ifndef _Included_com_jni_bus_JNI_Bus
#define _Included_com_jni_bus_JNI_Bus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_bus_JNI_Bus
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_bus_JNI_1Bus_init
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
